version: "3.9"

services:
  svelte:
    container_name: svelte_container
    build: .
    ports:
      - "4173:4173"

  flask:
    container_name: flask_container
    build: ./backend/flask_mssql_app
    ports:
      - "5000:5000"
